name: Update Calvin and Hobbes Feed

on:
  schedule:
    - cron: '0 7 * * *'  # Daily at 07:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code using GH_PAT
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run generator script
        run: python generate_calvin_feed.py

      - name: Touch file to ensure commit always happens
        run: |
          touch .last_run
          touch docs/feed.xml  # extra safety if needed

      - name: Show git status and diff (for debugging)
        run: |
          git status
          git diff || true

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/*.xml docs/*.html used_comics.json .last_run || true
          git commit -m "Update Calvin & Hobbes feed" --allow-empty
          git push
