name: Update Calvin and Hobbes Feed

on:
  schedule:
    - cron: '0 7 * * *'  # Daily at 07:00 UTC
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code using GH_PAT
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run generator script
        run: python generate_calvin_feed.py

      - name: Touch feed.xml to ensure Git detects it
        run: touch docs/feed.xml

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/*.xml docs/*.html used_comics.json || true
          git commit -m "Update feed" --allow-empty
          git push
